FROM debian:buster

RUN apt-get -y update; \
    apt-get -y install gcc; \
    apt-get -y install g++; \
    apt-get -y install haskell-platform; \
    apt-get -y install default-jre; \
    apt-get -y install default-jdk; \
    apt-get -y install nodejs; \
    apt-get -y install python3; \

